/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package pf.ide

import com.google.inject.Guice
import pf.PfRuntimeModule
import pf.PfStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class PfIdeSetup extends PfStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new PfRuntimeModule, new PfIdeModule))
	}
	
}
